# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sesionAdministradores.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sesionAdministradores(object):
    def setupUi(self, sesionAdministradores):
        sesionAdministradores.setObjectName("sesionAdministradores")
        sesionAdministradores.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(sesionAdministradores)
        self.centralwidget.setObjectName("centralwidget")
        sesionAdministradores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sesionAdministradores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        sesionAdministradores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sesionAdministradores)
        self.statusbar.setObjectName("statusbar")
        sesionAdministradores.setStatusBar(self.statusbar)

        self.retranslateUi(sesionAdministradores)
        QtCore.QMetaObject.connectSlotsByName(sesionAdministradores)

    def retranslateUi(self, sesionAdministradores):
        _translate = QtCore.QCoreApplication.translate
        sesionAdministradores.setWindowTitle(_translate("sesionAdministradores", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sesionAdministradores = QtWidgets.QMainWindow()
    ui = Ui_sesionAdministradores()
    ui.setupUi(sesionAdministradores)
    sesionAdministradores.show()
    sys.exit(app.exec_())
